// Corner v1 is an additive facade. /api/* routes remain backward compatible.
const routes=[
['get','/api/v1','getApiIndex','API index'],['get','/api/v1/live','getLiveness','Process liveness'],
['get','/api/v1/ready','getReadiness','Database and storage readiness'],
['get','/api/v1/health','getHealth','Service health'],['get','/api/v1/openapi.json','getOpenApi','OpenAPI specification'],
['get','/api/v1/posts','listPosts','Cursor-paginated published posts'],
['get','/api/v1/posts/{slug}','readPost','Read published post'],
['post','/api/v1/posts/{postId}/reactions','toggleReaction','Legacy non-idempotent reaction toggle'],
['put','/api/v1/posts/{postId}/reactions','setReaction','Idempotently set reaction'],
['delete','/api/v1/posts/{postId}/reactions','clearReaction','Idempotently remove reaction'],
['get','/api/v1/posts/{postId}/comments','listComments','Approved public comments'],
['post','/api/v1/posts/{postId}/comments','submitComment','Submit a moderated comment'],
['get','/api/v1/search','searchPosts','Search published posts'],
['get','/api/v1/status','getStatus','Current status and upcoming teasers'],
['get','/api/v1/realtime/stream','streamEvents','Replayable Server-Sent Events'],
['post','/api/v1/analytics/event','recordAnalyticsEvent','Record allowed first-party event'],
['post','/api/v1/auth/register','registerMember','Register private member and email a one-time verification link'],
['post','/api/v1/auth/login','loginMember','Sign in a verified member'],
['post','/api/v1/auth/admin/login','loginStaff','Sign in a Studio role, with authenticator verification when enabled'],
['post','/api/v1/auth/admin/register','registerInvitedStaff','Redeem a signed, expiring, owner-issued invitation'],
['post','/api/v1/auth/mfa/setup','beginMfa','Start encrypted authenticator enrolment'],
['post','/api/v1/auth/mfa/activate','activateMfa','Verify TOTP and obtain one-time recovery codes'],
['get','/api/v1/auth/session','getIdentitySession','Read current member or staff session'],
['post','/api/v1/auth/logout','logoutIdentity','Revoke identity session and clear both cookie scopes'],
['post','/api/v1/auth/email/verify','verifyIdentityEmail','Verify single-use email token'],
['post','/api/v1/auth/email/resend','resendIdentityEmail','Resend a short-lived verification token'],
['post','/api/v1/auth/email/change','requestIdentityEmailChange','Request a verified account email change'],
['post','/api/v1/auth/email/confirm','confirmIdentityEmailChange','Approve a one-time email change and revoke old sessions'],
['post','/api/v1/auth/password/forgot','requestPasswordReset','Issue generic reset acknowledgment without account enumeration'],
['post','/api/v1/auth/password/reset','resetIdentityPassword','Reset password with single-use token and revoke sessions'],
['post','/api/v1/auth/password/change','changeIdentityPassword','Change password and revoke all sessions'],
['get','/api/v1/me','readPrivateProfile','Get current private member/staff profile'],
['patch','/api/v1/me','updatePrivateProfile','Update display name, bio and private preferences'],
['get','/api/v1/me/preferences','getPrivatePreferences','Read member preference settings'],
['patch','/api/v1/me/preferences','updatePrivatePreferences','Update language and notifications settings'],
['get','/api/v1/me/sessions','listIdentitySessions','List current account sessions'],
['delete','/api/v1/me/sessions/{sessionId}','revokeIdentitySession','Revoke an account session'],
['get','/api/v1/me/bookmarks','listIdentityBookmarks','List privately bookmarked published posts'],
['post','/api/v1/me/bookmarks','createIdentityBookmark','Save a published post privately'],
['delete','/api/v1/me/bookmarks/{postId}','deleteIdentityBookmark','Remove a saved post'],
['post','/api/v1/me/export','exportIdentityData','Export personal profile/bookmark/session metadata'],
['post','/api/v1/me/deletion','requestIdentityDeletion','Submit a reviewed account-deletion request'],
['post','/api/v1/admin/invitations','inviteStudioAccount','Owner-only invitation for admin, editor or moderator'],
['post','/api/v1/admin/login','signInOwner','Owner login and session cookie'],
['post','/api/v1/admin/logout','signOutOwner','Revoke owner session'],
['get','/api/v1/admin/overview','getOwnerOverview','Owner dashboard summary'],
['get','/api/v1/admin/posts','listAdminPosts','List owner posts'],
['post','/api/v1/admin/posts','createPost','Create draft with 201 Location'],
['get','/api/v1/admin/posts/{postId}','readAdminPost','Read draft or published post'],
['patch','/api/v1/admin/posts/{postId}','updatePost','Update with optimistic version'],
['delete','/api/v1/admin/posts/{postId}','archiveAdminPost','Reversible soft-delete/archive'],
['post','/api/v1/admin/posts/{postId}/publish','publishPost','Publish post'],
['post','/api/v1/admin/posts/{postId}/archive','archivePost','Archive post'],
['post','/api/v1/admin/posts/{postId}/restore','restorePost','Restore archived post'],
['post','/api/v1/admin/posts/{postId}/schedule','schedulePost','Schedule post or yearly wish'],
['post','/api/v1/admin/posts/{postId}/duplicate','duplicatePost','Duplicate post'],
['put','/api/v1/admin/status','updatePublicStatus','Set published status'],
['get','/api/v1/admin/comments','listAdminComments','Moderation queue'],
['get','/api/v1/admin/comments/{commentId}','readAdminComment','Read private comment'],
['patch','/api/v1/admin/comments/{commentId}','moderateComment','Moderate comment'],
['delete','/api/v1/admin/comments/{commentId}','deleteComment','Soft-delete comment'],
['get','/api/v1/admin/media','listMedia','List media metadata'],
['post','/api/v1/admin/media/upload','uploadMedia','Validate and upload bytes'],
['get','/api/v1/admin/media/{mediaId}','getMedia','Read private media metadata'],
['patch','/api/v1/admin/media/{mediaId}','updateMedia','Update media metadata'],
['delete','/api/v1/admin/media/{mediaId}','deleteMedia','Delete media and bytes'],
['get','/api/v1/admin/settings','readSettings','Read publication settings'],
['put','/api/v1/admin/settings','updateSettings','Update publication settings'],
['get','/api/v1/admin/analytics/summary','readAnalytics','Read owner analytics'],
['get','/api/v1/admin/ops','readOperations','Read scheduler and health diagnostics'],
["get","/api/v1/search/advanced","advancedSearch","Advanced published story search"],
["get","/api/v1/archive","browseArchive","Public archive"],
["get","/api/v1/guestbook","listApprovedGuestbook","Approved guestbook"],
["post","/api/v1/guestbook","submitGuestbook","Moderated guestbook submission"],
["get","/api/v1/admin/v3/guestbook","listPendingGuestbook","Owner moderation queue"],
["patch","/api/v1/admin/v3/guestbook/{entryId}","reviewGuestbook","Approve or hide guestbook note"],
["post","/api/v1/follow","requestFollowing","Request double opt-in"],
["post","/api/v1/follow/verify","verifyFollowing","Confirm following"],
["post","/api/v1/follow/unsubscribe/request","requestUnsubscribe","Request opt-out"],
["post","/api/v1/follow/unsubscribe","unsubscribeFollowing","Confirm opt-out"],
["get","/api/v1/me/reading/{postId}","getReadingProgress","Private reading position"],
["put","/api/v1/me/reading/{postId}","saveReadingProgress","Save private position"],
["delete","/api/v1/me/reading/{postId}","removeReadingProgress","Remove saved position"],
["get","/api/v1/memories/timeline","listLifeTimeline","Published life milestones"],
["get","/api/v1/memories/albums","listMomentsAlbums","List safe published albums"],
["get","/api/v1/memories/albums/{slug}","getMomentsAlbum","Read public album"],
["get","/api/v1/memories/collections","listReadingCollections","Published reading series"],
["get","/api/v1/memories/collections/{slug}","getReadingCollection","Read series"],
["get","/api/v1/memories/now/history","getPublicNowHistory","Published Now history"],
["get","/api/v1/admin/v3/memories","getOwnerMemories","Memories Studio data"],
["get","/api/v1/admin/v3/milestones","getOwnerMilestones","Owner milestones"],
["post","/api/v1/admin/v3/milestones","createMilestone","Create milestone"],
["patch","/api/v1/admin/v3/milestones/{id}","editMilestone","Edit milestone"],
["delete","/api/v1/admin/v3/milestones/{id}","archiveMilestone","Archive milestone"],
["get","/api/v1/admin/v3/albums","getOwnerAlbums","Owner albums"],
["post","/api/v1/admin/v3/albums","createAlbum","Create album"],
["patch","/api/v1/admin/v3/albums/{id}","editAlbum","Edit album"],
["delete","/api/v1/admin/v3/albums/{id}","archiveAlbum","Archive album"],
["get","/api/v1/admin/v3/collections","getOwnerCollections","Owner collections"],
["post","/api/v1/admin/v3/collections","createCollection","Create collection"],
["patch","/api/v1/admin/v3/collections/{id}","editCollection","Edit collection"],
["delete","/api/v1/admin/v3/collections/{id}","archiveCollection","Archive collection"],
];
const json={'application/json':{schema:{type:'object'}}};
const reply=(description)=>({description,content:json});
const paths={};
for(const [method,url,id,summary] of routes){
 const op={operationId:id,summary,tags:[url.includes('/me')?'Account':url.includes('/auth/')?'Identity':url.includes('/admin/')?'Owner':'Public'],responses:{'200':reply('Success'),'400':reply('Invalid input'),'401':reply('Authentication required'),'403':reply('Forbidden'),'404':reply('Not found'),'429':reply('Too many requests')}};
 const placeholders=[...url.matchAll(/\{(\w+)\}/g)].map(m=>({in:'path',name:m[1],required:true,schema:{type:'string'}}));
 if(placeholders.length)op.parameters=placeholders;
 if(url.startsWith('/api/v1/me'))op.security=[{memberSession:[]},{ownerSession:[]}];
 if(url.includes('/admin/')&&!['signInOwner','loginStaff','registerInvitedStaff'].includes(id))op.security=[{ownerSession:[]}];
 if(['post','put','patch'].includes(method)&&!['signOutOwner','logoutIdentity','publishPost','archivePost','restorePost','duplicatePost'].includes(id))op.requestBody={required:true,content:json};
 if(id==='uploadMedia')op.requestBody={required:true,content:{'image/png':{schema:{type:'string',format:'binary'}},'image/jpeg':{schema:{type:'string',format:'binary'}},'video/mp4':{schema:{type:'string',format:'binary'}}}};
 if(id==='createPost')op.responses['201']=reply('Created; Location header points to resource');
 if(id==='getReadiness')op.responses['503']=reply('Storage unavailable');
 if(id==='streamEvents')op.responses['200']={description:'Event stream',content:{'text/event-stream':{schema:{type:'string'}}}};
 (paths[url]??={})[method]=op;
}
export const openApiDocument=(baseUrl)=>({
 openapi:'3.1.0',
 info:{title:"Vamsi's Corner REST API",version:'1.2.0',description:'Additive role-scoped identity and private profiles; public registration stays disabled until verified email delivery is configured. Invitations are owner-only, staff requires MFA, member and Studio cookies are separate. All mutations enforce same-origin CSRF controls. Legacy publishing routes remain compatible.'},
 servers:[{url:baseUrl}],tags:[{name:'Public'},{name:'Identity'},{name:'Account'},{name:'Owner'}],paths,
 components:{securitySchemes:{ownerSession:{type:'apiKey',in:'cookie',name:'corner_session'},memberSession:{type:'apiKey',in:'cookie',name:'corner_member_session'}}},
});
