import { config } from './config.mjs';
import { typeLabels, CATEGORIES, REACTIONS, statuses, now } from './domain.mjs';
export function escapeHtml(value=''){return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;')}
const e=escapeHtml;
const dateLabel=(value)=>value?new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeZone:config.timezone}).format(new Date(value)):'';
const icon=(name)=>({arrow:'↗',right:'→',down:'↓',more:'···',search:'⌕',plus:'＋',close:'×'}[name]||name);
export const samples=()=>[
 {id:'sample-1',slug:'sample-a-small-new-beginning',type:'announcement',title:'A small new beginning.',excerpt:'A quiet space for what matters next.',body:'A place to collect short updates, ideas, and good things worth remembering. This is illustrative sample copy for local preview only.',emoji:'✳',published_at:new Date(Date.now()-2*3600000).toISOString(),featured:true,pinned:false,allow_comments:true,allow_reactions:true,version:1,tags:['Sample','Corner'],demo:true},
 {id:'sample-2',slug:'sample-here-is-to-good-news',type:'wish',title:'Here’s to good news. ✨',excerpt:'For the little wins, and all the ones still coming.',body:'A short example wish. Scheduling will automatically publish real wishes at the exact selected time.',emoji:'✨',published_at:new Date(Date.now()-22*3600000).toISOString(),featured:false,pinned:false,allow_comments:false,allow_reactions:true,version:1,tags:['Sample'],demo:true},
 {id:'sample-3',slug:'sample-build-note-001',type:'build',title:'It starts small.',excerpt:'01 / Building the corner',body:'An illustrative build note for the interface preview.',emoji:'↗',published_at:new Date(Date.now()-2*86400000).toISOString(),featured:false,pinned:false,allow_comments:false,allow_reactions:true,version:1,tags:['Sample','Building'],demo:true},
 {id:'sample-4',slug:'sample-simple-systems',type:'tech_note',title:'Simple systems age well.',excerpt:'A tiny idea worth keeping.',body:'Good systems make the hard things possible without making the easy things complicated. This text is an example.',emoji:'⌘',published_at:new Date(Date.now()-4*86400000).toISOString(),featured:false,pinned:false,allow_comments:false,allow_reactions:true,version:1,tags:['Sample','Notes'],demo:true},
 {id:'sample-5',slug:'sample-one-little-moment',type:'moment',title:'One little moment.',excerpt:'Some things deserve a space of their own.',body:'A sample moment card. Published moments can have real images or video, with focal points and captions.',emoji:'☼',published_at:new Date(Date.now()-8*86400000).toISOString(),featured:false,pinned:false,allow_comments:true,allow_reactions:true,version:1,tags:['Sample'],demo:true},
 {id:'sample-6',slug:'sample-reflection',type:'journal',title:'On noticing more.',excerpt:'Finding meaning in quieter details.',body:'An example journal entry. Long-form writing belongs inside the post, not all over the feed.',emoji:'✺',published_at:new Date(Date.now()-16*86400000).toISOString(),featured:false,pinned:false,allow_comments:false,allow_reactions:true,version:1,tags:['Sample'],demo:true},
];
const safeLink=(slug)=>'/post/'+encodeURIComponent(slug);
export function renderMedia(media=[]){if(!media.length)return '';const m=media[0],src='/media/'+encodeURIComponent(m.storage_key);return m.mime_type.startsWith('video/')?`<div class="card-media"><video controls preload="none" playsinline aria-label="${e(m.alt_text||'Video')}"><source src="${src}" type="${e(m.mime_type)}"></video></div>`:`<div class="card-media"><img src="${src}" loading="lazy" alt="${e(m.alt_text||'Post image')}" style="object-position:${Number(m.focal_x||.5)*100}% ${Number(m.focal_y||.5)*100}%"></div>`}
export function card(post,index=0,{featured=false,reactions={},comments=0,media=[]}={}){
  const tag=post.demo?'SAMPLE':(statuses(post)[0]||'');
  const isHero=featured||!!post.featured;
  return `<article class="story ${isHero?'story-featured':''} story-${e(post.type)}" data-id="${e(post.id)}" data-version="${post.version||1}">
    <div class="story-top"><span class="meta category">${e(typeLabels[post.type]||'UPDATE')}</span>${tag?`<span class="status-tag">${e(tag)}</span>`:''}</div>
    ${!media.length&&(post.type==='moment'||(isHero&&post.type==='announcement'))?`<div class="story-art art-${e(post.type)}" aria-hidden="true"><span class="art-orbit art-orbit-a"></span><span class="art-orbit art-orbit-b"></span><span class="art-glyph">${e(post.emoji||'✳')}</span><span class="art-caption">${post.demo?'An illustrative visual':'VAMSI’S CORNER'}</span></div>`:''}
    ${renderMedia(media)}
    <div class="story-copy"><p class="story-count">${String(index+1).padStart(2,'0')} / ${e(dateLabel(post.published_at))}</p>
    <h2><a href="${safeLink(post.slug)}">${e(post.title)}</a></h2>
    ${post.excerpt?`<p class="story-excerpt">${e(post.excerpt)}</p>`:''}
    <div class="story-bottom"><span class="read-meta">${post.type==='journal'?'JOURNAL':post.type==='build'?'BUILD LOG':'READ UPDATE'}</span><a class="read-link" href="${safeLink(post.slug)}" aria-label="Read ${e(post.title)}">Read <span aria-hidden="true">↗</span></a></div></div>
  </article>`;
}
export function basePage({title='',description='',path='/',content='',initial={},noindex=false,article=false,language='en',alternates=[]}){
  const fullTitle=title?title+' — '+config.siteTitle:config.siteTitle;
  const desc=description||'Thoughts, updates & celebrations — a quiet space for things worth keeping.';
  const canonical=config.siteUrl.replace(/\/$/,'')+path;
  const state=JSON.stringify(initial).replaceAll('<','\\u003c').replaceAll('>','\\u003e').replaceAll('&','\\u0026');
  return `<!doctype html><html lang="${e(language)}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#f8f7f3"><title>${e(fullTitle)}</title><meta name="description" content="${e(desc)}"><link rel="canonical" href="${e(canonical)}">${alternates.map(a=>'<link rel="alternate" hreflang="'+e(a.lang)+'" href="'+e(a.url)+'">').join('')}<meta property="og:type" content="${article?'article':'website'}"><meta property="og:site_name" content="${e(config.siteTitle)}"><meta property="og:title" content="${e(fullTitle)}"><meta property="og:description" content="${e(desc)}"><meta property="og:url" content="${e(canonical)}"><meta property="og:image" content="${e(config.siteUrl+'/og.svg')}"><meta name="twitter:card" content="summary_large_image">${noindex?'<meta name="robots" content="noindex,nofollow">':''}<link rel="alternate" type="application/rss+xml" title="Corner RSS" href="/rss.xml"><link rel="alternate" type="application/atom+xml" title="Corner Atom" href="/atom.xml"><link rel="icon" href="/mark.svg" type="image/svg+xml"><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/v3.css"><link rel="stylesheet" href="/v3-memories.css">${initial.page==='wishes'?'<link rel="stylesheet" href="/v3-wishes.css">':''}${(['insights','languages'].includes(initial.page)||(initial.page==='detail'&&initial.hasLanguages))?'<link rel="stylesheet" href="/v3-phase4.css">':''}<link rel="stylesheet" href="/magic.css">${initial.page==='account'?'<link rel="stylesheet" href="/account.css">':''}<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':article?'BlogPosting':'WebSite',name:fullTitle,url:canonical,description:desc}).replaceAll('<','\\u003c')}</script><script>window.__CORNER__=${state}</script><script src="/app.js" defer></script><script src="/v3.js" defer></script><script src="/v3-memories.js" defer></script>${initial.page==='wishes'?'<script src="/v3-wishes.js" defer></script>':''}${initial.page==='languages'?'<script src="/v3-phase4.js" defer></script>':''}<script src="/nav.js" defer></script></head><body><a class="skip-link" href="#content">Skip to content</a>${content}</body></html>`;
}
export function header(active='Latest',status=null){return `<header class="site-header"><div class="header-row"><a class="brand" href="/" aria-label="Vamsi's Corner — Home"><span class="brand-mark" aria-hidden="true">✳</span><span class="brand-type"><strong>Vamsi’s Corner<span>.</span></strong><small>NOTES FROM THE IN-BETWEEN</small></span></a><div class="header-right"><a class="header-now" href="/now"><span class="live-dot"></span>${status?e(status.label):'A place to keep things'}</a><button type="button" class="icon-button" data-search-open aria-label="Open search"><svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"><circle cx="10.8" cy="10.8" r="6.4"/><path d="m16 16 4.6 4.6"/></svg></button><a class="header-admin" href="/admin" aria-label="Owner sign-in">↗</a></div></div><nav class="category-tabs" aria-label="Content categories">${CATEGORIES.map(cat=>`<a href="${cat==='Latest'?'/':'/category/'+encodeURIComponent(cat.toLowerCase())}" class="${active===cat?'is-active':''}" ${active===cat?'aria-current="page"':''}>${cat}</a>`).join('')}<a class="category-account" href="/login">Account ↗</a></nav></header>`}
export function footer(){return `<footer class="site-footer"><div><a class="footer-brand" href="/">Vamsi’s Corner<span>.</span></a><p>A small place for big and little things.</p></div><div class="footer-links"><a href="/about">About</a><a href="/login">Member sign-in</a><a href="/register">Register</a>${process.env.CORNER_V3_SEARCH==='1'?'<a href="/search">Explore</a><a href="/archive">Archive</a>':''}${process.env.CORNER_V3_MEMORIES==='1'?'<a href="/timeline">Timeline</a><a href="/moments">Moments</a><a href="/collections">Collections</a>':''}${process.env.CORNER_V3_GUESTBOOK==='1'?'<a href="/guestbook">Guestbook</a>':''}${process.env.CORNER_V3_FOLLOW==='1'?'<a href="/follow">Follow</a>':''}<a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="mailto:connect@vamsimarripudi.me">Say hello ↗</a></div><p class="footer-meta">Made with care. <span>© ${new Date().getFullYear()} Vamsi Marripudi</span></p></footer>`}
export function searchDialog(){return `<dialog class="search-dialog" id="search-dialog" aria-labelledby="search-heading"><div class="search-dialog-head"><p id="search-heading">SEARCH THE CORNER</p><button data-search-close aria-label="Close search">×</button></div><label for="search-input" class="sr-only">Search posts and tags</label><div class="search-field"><span aria-hidden="true">⌕</span><input id="search-input" placeholder="An idea, a moment, a word…" autocomplete="off" maxlength="100"></div><div class="search-results" id="search-results"><p>Start with a word.</p></div><p class="search-footer">ESC to close <span>↗</span> ENTER to open</p></dialog>`}
export function hero(status,featured,upcoming=[]){const first=featured?`<a href="${safeLink(featured.slug)}">${e(featured.title)} <span>↗</span></a>`:'<span>Your next story starts here.</span>';return `<section class="hero-intro" aria-labelledby="hero-title"><div class="hero-content"><div class="hero-kicker"><span class="hero-star">✳</span> AN OPEN NOTEBOOK <span class="hero-sep">/</span> EST. NOW</div><h1 id="hero-title">Thoughts, updates<br><em>& celebrations.</em><span class="hero-spark" aria-hidden="true">✦</span></h1><p>Small notes on what I’m building, learning, feeling and celebrating. A little of everything, all in one place.</p><div class="hero-cta"><a href="#feed" class="hero-link">Explore the latest <span aria-hidden="true">↓</span></a><span class="hero-quiet">A quiet feed. Always open.</span></div></div><div class="hero-aside"><div class="now-panel"><span class="aside-cap">CURRENTLY <span>↗</span></span><div class="now-status"><span class="live-dot"></span><strong>${e(status?.label||'Keeping a little corner alive.')}</strong></div><p>${e(status?.detail||'The space is taking shape, one note at a time.')}</p><span class="aside-rule"></span><span class="aside-bottom">LAST UPDATED <span>${status?e(dateLabel(status.updatedAt)):'WHEN THERE’S SOMETHING TO SAY'}</span></span></div><div class="editorial-chip"><span>IN THE SPOTLIGHT</span>${first}</div>${upcoming.length?`<div class="next-wish"><span>COMING UP</span><p>${e(upcoming[0].emoji||'✨')} ${e(upcoming[0].title)}</p><small>${e(dateLabel(upcoming[0].scheduled_at))}</small></div>`:''}</div></section>`}
export function feedPage({posts=[],status,active='Latest',featured,upcoming=[],cursor,tag='',demo=false,mediaByPost={},eventCursor=0,onThisDay=[]}){
  const body=`${header(active,status)}<main id="content" class="shell">${active==='Latest'?hero(status,featured,upcoming):`<section class="category-hero"><p class="eyebrow">THE CORNER / COLLECTIONS</p><h1>${e(active)}<span>.</span></h1><p>${active==='Wishes'?'Good things worth celebrating.':active==='Builds'?'Small steps, real progress.':active==='Notes'?'Ideas worth remembering.':active==='Journal'?'A place to slow down and write.':'Scenes and little memories.'}</p></section>`}${active==='Latest'&&onThisDay.length?`<section class="on-this-day"><p class="eyebrow">ON THIS DAY</p><div><h2>Worth remembering.</h2>${onThisDay.map(p=>`<a href="${safeLink(p.slug)}">${e(p.title)} <span>↗</span></a>`).join('')}</div></section>`:''}<section id="feed" class="feed-section" aria-labelledby="feed-heading"><div class="feed-heading"><div><p class="eyebrow">${active==='Latest'?'THE LATEST FROM HERE':e(active.toUpperCase())} ${demo?'<span class="demo-pill">SAMPLE CONTENT</span>':''}</p><h2 id="feed-heading">${active==='Latest'?'A little of everything.':active}</h2></div><span class="feed-updated">${posts.length?'FRESHLY PICKED / STORIES':'MORE TO COME'}</span></div><div class="new-updates" data-new-updates hidden><button type="button" data-apply-updates>↑ <span>1 new update</span></button></div>${posts.length?`<div class="stories" id="stories">${posts.map((p,i)=>card(p,i,{featured:i===0&&p.featured,media:mediaByPost[p.id]||[]})).join('')}</div>`:`<div class="empty-feed"><span aria-hidden="true">✳</span><h3>Nothing here yet.</h3><p>The next note will find its place soon.</p></div>`}${cursor?`<button class="load-more" data-load-more data-cursor="${e(cursor)}">More from the corner <span>↓</span></button>`:''}<p class="end-mark">YOU’VE CAUGHT UP <span>✳</span> MORE SOON</p></section><section class="about-stripe"><div><p class="eyebrow">ABOUT THIS SPACE</p><h2>Personal, by design.</h2></div><p>Not a feed to keep up with. Just an archive of things that mattered enough to write down. <a href="/about">A little more about it ↗</a></p></section></main>${footer()}${searchDialog()}<div class="toast-stack" id="toast-stack" aria-live="polite"></div>`;
  return basePage({path:active==='Latest'?'/':'/category/'+active.toLowerCase(),title:active==='Latest'?'':'The '+active,content:body,initial:{page:'feed',category:active,demo,eventCursor}});
}
export function detailPage({post,comments=[],counts={},next=null,media=[],languages=[],activeLanguage='en'}){
 const bodyHtml=e(post.body).split(/\n{2,}/).map(s=>`<p>${s.replace(/\n/g,'<br>')}</p>`).join('');
 const linkOf=code=>'/post/'+encodeURIComponent(post.slug)+(code==='en'?'':'?lang='+encodeURIComponent(code));
 const labels={en:'English',te:'తెలుగు',hi:'हिन्दी'};
 const languageNav=languages.length>1?'<nav class="v3a-language-picker" aria-label="Read in another language">'+languages.map(code=>'<a href="'+linkOf(code)+'" lang="'+code+'"'+(code===activeLanguage?' aria-current="page"':'')+'>'+e(labels[code]||code)+'</a>').join('')+'</nav>':'';
 let markup=`${header()}<main id="content" class="shell article-shell"><nav class="crumb"><a href="/">CORNER</a><span>/</span><span>${e(typeLabels[post.type])}</span></nav>${languageNav}<article class="post-article" data-post="${e(post.id)}"><header class="post-heading"><div class="post-caps"><span>${e(typeLabels[post.type])}</span>${post.demo?'<span class="demo-pill">SAMPLE</span>':''}<span>${e(dateLabel(post.published_at))}</span></div><h1>${e(post.title)}</h1>${post.excerpt?`<p>${e(post.excerpt)}</p>`:''}<div class="post-byline"><span class="avatar">V.</span><div><strong>Vamsi</strong><span>${Math.max(1,Math.ceil(post.body.split(/\s+/).length/220))} MIN READ</span></div><a href="#share" class="share-link">Share ↗</a></div></header>${post.type==='moment'&&!media.length?`<div class="detail-art" aria-hidden="true">${e(post.emoji||'✺')}</div>`:''}${renderMedia(media)}<div class="post-body">${bodyHtml||'<p>A small moment, shared here.</p>'}</div><div class="post-end">✳</div><div class="post-actions"><div><p class="eyebrow">LEAVE A LITTLE REACTION</p>${post.allow_reactions&&!post.demo?`<div class="reactions" data-post-id="${e(post.id)}">${REACTIONS.map(x=>`<button type="button" data-reaction="${e(x)}" aria-label="React ${e(x)}">${x} <span>${Number(counts[x]||0)}</span></button>`).join('')}</div>`:'<p class="action-note">A quiet appreciation is enough.</p>'}</div><div id="share" class="post-share"><button type="button" data-bookmark-post data-post-id="${e(post.id)}" hidden>Save for later ☆</button>${process.env.CORNER_V3_READING==='1'&&!post.demo?'<button type="button" data-v3-save-progress data-post-id="'+e(post.id)+'">Save reading position ◇</button>':''}<button type="button" data-copy-url>Copy link ↗</button></div></div>${post.allow_comments&&!post.demo?`<section class="comments"><div class="comments-title"><p class="eyebrow">THE CONVERSATION</p><h2>A few words back.</h2></div><div id="comments-list">${comments.length?comments.map(c=>`<article class="comment"><strong>${e(c.author_name)}</strong><time>${e(dateLabel(c.created_at))}</time><p>${e(c.body)}</p></article>`).join(''):'<p class="empty-comments">No comments yet.</p>'}</div><form id="comment-form" data-post-id="${e(post.id)}"><label for="comment-name">Name</label><input id="comment-name" name="name" maxlength="60" minlength="2" required placeholder="What should I call you?"><label for="comment-text">Your note</label><textarea id="comment-text" name="body" required minlength="3" maxlength="1000" placeholder="Something thoughtful, kind, or curious…"></textarea><button type="submit">Send comment <span>↗</span></button><small>Comments appear after review.</small></form></section>`:''}</article>${next?`<aside class="next-story"><p class="eyebrow">KEEP READING</p><a href="${safeLink(next.slug)}"><span>${e(next.title)}</span><b>↗</b></a></aside>`:''}</main>${footer()}${searchDialog()}<div class="toast-stack" id="toast-stack" aria-live="polite"></div>`;
 return basePage({title:post.title,description:post.excerpt||post.body.slice(0,150),path:linkOf(activeLanguage),content:markup,article:true,language:activeLanguage==='te'?'te-IN':activeLanguage==='hi'?'hi-IN':'en',alternates:languages.map(code=>({lang:code==='en'?'en':code+'-IN',url:config.siteUrl+linkOf(code)})),initial:{page:'detail',postId:post.id,demo:!!post.demo,hasLanguages:languages.length>1}});
}
export function simplePage({title,lead,body,path}){let html=`${header()}<main id="content" class="shell simple-page"><p class="eyebrow">THE CORNER / ${e(title.toUpperCase())}</p><h1>${e(title)}<span>.</span></h1><p class="simple-lede">${e(lead)}</p><div class="simple-text">${body}</div><a class="back-link" href="/">← Back to the corner</a></main>${footer()}${searchDialog()}<div class="toast-stack" id="toast-stack" aria-live="polite"></div>`;return basePage({title,path,content:html})}
export function adminPage({owner=null,status=null}){
 const login=`<div class="signin-wrap"><div class="signin-box"><div class="admin-signin-mark">✳</div><p class="eyebrow">THE PRIVATE SIDE</p><h1>Welcome back.</h1><p>One small place to make everything happen.</p><form id="admin-login"><label>Email<input type="email" name="email" autocomplete="username" required placeholder="you@example.com"></label><label>Password<input type="password" name="password" autocomplete="current-password" required minlength="12" placeholder="Your secure password"></label><label class="admin-mfa-field"><span>Authenticator code (when enabled)</span><input type="text" name="code" inputmode="numeric" autocomplete="one-time-code" maxlength="19" placeholder="Six-digit or recovery code"></label><button type="submit">Open the Corner <span>↗</span></button><p class="admin-message" role="status" id="login-message"></p></form><a href="/">← Back to the public site</a></div></div>`;
 const views=owner?.role==='moderator'?[['comments','Comments'],...(process.env.CORNER_V3_GUESTBOOK==='1'?[['guestbook','Guestbook']]:[])]:owner?.role==='editor'?[['posts','Posts'],['media','Media']]:[['overview','Overview'],['posts','Posts'],['media','Media'],['comments','Comments'],...(process.env.CORNER_V3_GUESTBOOK==='1'?[['guestbook','Guestbook']]:[]),['analytics','Analytics'],['settings','Settings']];
 const ownerV3Links=owner?.role==='owner'?
  [['CORNER_V3_MEMORIES','/admin/v3/memories','Memories'],
   ['CORNER_V3_WISHES','/admin/v3/wishes','Wishes'],
   ['CORNER_V3_INSIGHTS','/admin/v3/insights','Insights'],
   ['CORNER_V3_LANGUAGES','/admin/v3/languages','Languages']]
    .filter(([flag])=>process.env[flag]==='1')
    .map(([,href,label])=>'<a class="admin-v3-link" href="'+href+'">'+label+' ↗</a>').join(''):'';
 const dashboard=`<div class="admin-shell"><aside class="admin-sidebar"><a class="admin-brand" href="/admin"><span>✳</span> Vamsi’s Corner<small>STUDIO</small></a><div class="admin-nav">${views.map(([id,title])=>`<button type="button" data-admin-view="${id}" class="${id==='overview'?'is-active':''}">${e(title)} <span>↗</span></button>`).join('')}${process.env.CORNER_V3_GUESTBOOK==='1'&&['owner','admin','moderator'].includes(owner?.role)?'<a class="admin-v3-link" href="/admin/v3/guestbook">Guestbook review ↗</a>':''}${ownerV3Links}</div><div class="admin-sidebar-footer"><a href="/" target="_blank">View live corner ↗</a><button id="admin-logout" type="button">Sign out</button></div></aside><div class="admin-main"><header class="admin-top"><div><p class="eyebrow">OWNER WORKSPACE</p><h1 id="admin-heading">Overview<span>.</span></h1></div><div><span class="admin-owner-dot">●</span> ${e(owner?.email||'')} <button class="admin-mobile-nav" id="admin-nav-toggle">Menu ↓</button></div></header><div id="admin-view" class="admin-view"><div class="admin-loading">Preparing your workspace…</div></div></div></div>`;
 return basePage({title:'Studio',path:'/admin',noindex:true,content:(owner?dashboard:login)+`<div class="toast-stack" id="toast-stack" aria-live="polite"></div><script src="/admin.js" defer></script>`,initial:{page:'admin',authenticated:!!owner,status,ownerRole:owner?.role||null}});
}
