import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { passwordHash } from '../src/auth.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const sleep=(ms)=>new Promise(resolve=>setTimeout(resolve,ms));
const port=46500+Math.floor(Math.random()*800);
const base=`http://127.0.0.1:${port}`;
const folder=fs.mkdtempSync(path.join(os.tmpdir(),'corner-api-'));
let child;
const ADMIN_EMAIL='test-owner@example.com';
const ADMIN_PASSWORD='a-safe-temporary-password-1234!';
async function request(uri,method='GET',body,cookie){const opts={method,headers:{Origin:base}};if(body!==undefined){opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(body)}if(cookie)opts.headers.Cookie=cookie;return fetch(base+uri,opts)}
async function parsed(res){let json=await res.json();return {status:res.status,...json}}
test('API end-to-end: secure owner publishing, realtime persistence, comments, reactions and search',async t=>{
 child=spawn(process.execPath,['--no-warnings','src/server.mjs'],{cwd:root,env:{...process.env,DB_PATH:path.join(folder,'integration.sqlite'),DEMO_CONTENT:'0',NODE_ENV:'development',PORT:String(port),HOST:'127.0.0.1',SITE_URL:base,ADMIN_EMAIL,ADMIN_PASSWORD_HASH:passwordHash(ADMIN_PASSWORD),SESSION_SECRET:crypto.randomBytes(32).toString('hex')},stdio:['ignore','pipe','pipe']});
 child.stderr.on('data',d=>{let text=String(d);if(!text.includes('Warning:'))console.error('CHILD',text)});
 t.after(async()=>{child?.kill('SIGTERM');await sleep(90);fs.rmSync(folder,{recursive:true,force:true})});
 let ready=false;for(let i=0;i<60;i++){try{let r=await fetch(base+'/api/health');if(r.ok){ready=true;break}}catch{}await sleep(80)}assert.equal(ready,true,'backend ready');
 const home=await fetch(base+'/');assert.equal(home.status,200);const html=await home.text();assert.ok(html.includes('Thoughts, updates'));assert.ok(html.includes('Nothing here yet.'));
 const noAuth=await parsed(await request('/api/admin/posts','POST',{title:'No access'}));assert.equal(noAuth.status,401);
 const invalid=await parsed(await request('/api/admin/login','POST',{email:ADMIN_EMAIL,password:'bad'}));assert.equal(invalid.status,401);
 const authResponse=await request('/api/admin/login','POST',{email:ADMIN_EMAIL,password:ADMIN_PASSWORD});assert.equal(authResponse.status,200);let cookie=authResponse.headers.get('set-cookie')?.split(';')[0];assert.ok(cookie?.startsWith('corner_session='));
 const draft=await parsed(await request('/api/admin/posts','POST',{title:'A tiny verified build',body:'An exact end-to-end publishing check.',type:'build',excerpt:'Small systems, built carefully.',allowComments:true},cookie));assert.equal(draft.status,200);let post=draft.data;assert.equal(post.state,'draft');
 const feedBefore=await parsed(await request('/api/posts'));assert.equal(feedBefore.data.length,0,'draft not public');
 // Media is private until publication, and only the owner can preview drafts.
 const imageFixture=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/V3sAAAAASUVORK5CYII=','base64');
 const videoFixture=Buffer.concat([Buffer.from([0,0,0,24]),Buffer.from('ftypisom'),Buffer.alloc(35,0x41)]);
 const upload=(type,bytes,alt='A synthetic test image')=>fetch(base+'/api/admin/media/upload?postId='+encodeURIComponent(post.id)+'&alt='+encodeURIComponent(alt),{method:'POST',headers:{Origin:base,Cookie:cookie,'Content-Type':type},body:bytes});
 const deniedUpload=await fetch(base+'/api/admin/media/upload?postId='+encodeURIComponent(post.id)+'&alt=QA',{method:'POST',headers:{Origin:'https://forged.example',Cookie:cookie,'Content-Type':'image/png'},body:imageFixture});
 assert.equal(deniedUpload.status,403,'cross-origin upload denied');
 assert.equal((await upload('image/jpeg',imageFixture)).status,415,'invalid declared MIME rejected');
 assert.equal((await upload('image/png',imageFixture,'')).status,400,'image alt text required');
 const imageSaved=await parsed(await upload('image/png',imageFixture));assert.equal(imageSaved.status,200);const imageUrl=imageSaved.data.url;
 assert.match(imageUrl,/^\/media\/[A-Za-z0-9_-]+\.png$/);
 assert.equal((await fetch(base+imageUrl)).status,404,'unpublished image is private');
 let imagePreview=await fetch(base+imageUrl,{headers:{Cookie:cookie}});
 assert.equal(imagePreview.status,200,'owner previews draft image');
 assert.deepEqual(Buffer.from(await imagePreview.arrayBuffer()),imageFixture);
 const videoSaved=await parsed(await upload('video/mp4',videoFixture));assert.equal(videoSaved.status,200);const videoUrl=videoSaved.data.url;
 assert.equal((await fetch(base+videoUrl)).status,404,'unpublished video is private');
 // SSE must deliver post publication rather than only establish a connection.
 const eventStream=await fetch(base+'/api/realtime/stream');assert.equal(eventStream.status,200);
 const eventReader=eventStream.body.getReader();
 assert.match(new TextDecoder().decode((await eventReader.read()).value),/connected/);
 const invalidOrigin=await fetch(base+'/api/admin/posts/'+post.id+'/publish',{method:'POST',headers:{Origin:'https://evil.example',Cookie:cookie,'Content-Type':'application/json'}});assert.equal(invalidOrigin.status,403);
 const published=await parsed(await request('/api/admin/posts/'+post.id+'/publish','POST',{},cookie));assert.equal(published.status,200);
 let eventText='';
 const eventResult=await Promise.race([eventReader.read(),new Promise(resolve=>setTimeout(()=>resolve(null),4000))]);
 if(eventResult?.value)eventText=new TextDecoder().decode(eventResult.value);
 await eventReader.cancel();
 assert.match(eventText,/event: post\.published/,'real-time publication event delivered');
 const publicImage=await fetch(base+imageUrl);assert.equal(publicImage.status,200,'published image visible');
 assert.equal(publicImage.headers.get('content-type'),'image/png');
 assert.deepEqual(Buffer.from(await publicImage.arrayBuffer()),imageFixture);
 const videoRange=await fetch(base+videoUrl,{headers:{Range:'bytes=0-11'}});assert.equal(videoRange.status,206,'video byte ranges supported');
 assert.equal(videoRange.headers.get('content-range'),`bytes 0-11/${videoFixture.length}`);
 assert.deepEqual(Buffer.from(await videoRange.arrayBuffer()),videoFixture.subarray(0,12));
 assert.equal((await fetch(base+videoUrl,{headers:{Range:'bytes=99999-'}})).status,416,'invalid video range rejected');
 const postResponse=await parsed(await request('/api/posts/'+post.slug));assert.equal(postResponse.status,200);assert.equal(postResponse.data.post.title,'A tiny verified build');
 const feed=await parsed(await request('/api/posts'));assert.equal(feed.data.length,1);
 const search=await parsed(await request('/api/search?q=verified'));assert.equal(search.data.length,1);
 const react=await parsed(await request('/api/posts/'+post.id+'/reactions','POST',{reaction:'❤️'}));assert.equal(react.data.counts['❤️'],1);
 const comment=await parsed(await request('/api/posts/'+post.id+'/comments','POST',{name:'Reader',body:'What a thoughtful tiny note.'}));assert.equal(comment.data.state,'pending');
 const publicComments=await parsed(await request('/api/posts/'+post.id+'/comments'));assert.equal(publicComments.data.length,0);
 const pending=await parsed(await request('/api/admin/comments','GET',undefined,cookie));assert.equal(pending.data.length,1);
 const approved=await parsed(await request('/api/admin/comments/'+pending.data[0].id+'/approve','POST',{},cookie));assert.equal(approved.data.state,'approved');
 const after=await parsed(await request('/api/posts/'+post.id+'/comments'));assert.equal(after.data.length,1);
 const status=await parsed(await request('/api/admin/status','PUT',{label:'Testing the corner',detail:'Everything is local and real.',isActive:true},cookie));assert.equal(status.data.label,'Testing the corner');
 const publicStatus=await parsed(await request('/api/status'));assert.equal(publicStatus.data.status.label,'Testing the corner');
 const stream=await fetch(base+'/api/realtime/stream');assert.equal(stream.headers.get('content-type'),'text/event-stream');stream.body.cancel();
 const sitemap=await(await fetch(base+'/sitemap.xml')).text();assert.ok(sitemap.includes('/post/'+post.slug));assert.ok(!sitemap.includes('/admin'));
 const signOut=await parsed(await request('/api/admin/logout','POST',{},cookie));assert.equal(signOut.data.authenticated,false);
 const afterLogout=await parsed(await request('/api/admin/posts','GET',undefined,cookie));assert.equal(afterLogout.status,401);
 console.log('HTTP integration: owner login, create, publish, search, reactions, moderation, status, SSE, sitemap and logout verified');
});
