import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { passwordHash } from '../src/auth.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const sleep=(ms)=>new Promise(resolve=>setTimeout(resolve,ms));
const port=46500+Math.floor(Math.random()*800);
const base=`http://127.0.0.1:${port}`;
const folder=fs.mkdtempSync(path.join(os.tmpdir(),'corner-api-'));
let child;
const ADMIN_EMAIL='test-owner@example.com';
const ADMIN_PASSWORD='a-safe-temporary-password-1234!';
async function request(uri,method='GET',body,cookie){const opts={method,headers:{Origin:base}};if(body!==undefined){opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(body)}if(cookie)opts.headers.Cookie=cookie;return fetch(base+uri,opts)}
async function parsed(res){let json=await res.json();return {status:res.status,...json}}
test('API end-to-end: secure owner publishing, realtime persistence, comments, reactions and search',async t=>{
 child=spawn(process.execPath,['--no-warnings','src/server.mjs'],{cwd:root,env:{...process.env,DB_PATH:path.join(folder,'integration.sqlite'),DEMO_CONTENT:'0',NODE_ENV:'development',PORT:String(port),HOST:'127.0.0.1',SITE_URL:base,ADMIN_EMAIL,ADMIN_PASSWORD_HASH:passwordHash(ADMIN_PASSWORD),SESSION_SECRET:crypto.randomBytes(32).toString('hex')},stdio:['ignore','pipe','pipe']});
 child.stderr.on('data',d=>{let text=String(d);if(!text.includes('Warning:'))console.error('CHILD',text)});
 t.after(async()=>{child?.kill('SIGTERM');await sleep(90);fs.rmSync(folder,{recursive:true,force:true})});
 let ready=false;for(let i=0;i<60;i++){try{let r=await fetch(base+'/api/health');if(r.ok){ready=true;break}}catch{}await sleep(80)}assert.equal(ready,true,'backend ready');
 const home=await fetch(base+'/');assert.equal(home.status,200);const html=await home.text();assert.ok(html.includes('Thoughts, updates'));assert.ok(html.includes('Nothing here yet.'));
 const noAuth=await parsed(await request('/api/admin/posts','POST',{title:'No access'}));assert.equal(noAuth.status,401);
 const invalid=await parsed(await request('/api/admin/login','POST',{email:ADMIN_EMAIL,password:'bad'}));assert.equal(invalid.status,401);
 const authResponse=await request('/api/admin/login','POST',{email:ADMIN_EMAIL,password:ADMIN_PASSWORD});assert.equal(authResponse.status,200);let cookie=authResponse.headers.get('set-cookie')?.split(';')[0];assert.ok(cookie?.startsWith('corner_session='));
 const draft=await parsed(await request('/api/admin/posts','POST',{title:'A tiny verified build',body:'An exact end-to-end publishing check.',type:'build',excerpt:'Small systems, built carefully.',allowComments:true},cookie));assert.equal(draft.status,200);let post=draft.data;assert.equal(post.state,'draft');
 const feedBefore=await parsed(await request('/api/posts'));assert.equal(feedBefore.data.length,0,'draft not public');
 const invalidOrigin=await fetch(base+'/api/admin/posts/'+post.id+'/publish',{method:'POST',headers:{Origin:'https://evil.example',Cookie:cookie,'Content-Type':'application/json'}});assert.equal(invalidOrigin.status,403);
 const published=await parsed(await request('/api/admin/posts/'+post.id+'/publish','POST',{},cookie));assert.equal(published.status,200);
 const postResponse=await parsed(await request('/api/posts/'+post.slug));assert.equal(postResponse.status,200);assert.equal(postResponse.data.post.title,'A tiny verified build');
 const feed=await parsed(await request('/api/posts'));assert.equal(feed.data.length,1);
 const search=await parsed(await request('/api/search?q=verified'));assert.equal(search.data.length,1);
 const react=await parsed(await request('/api/posts/'+post.id+'/reactions','POST',{reaction:'❤️'}));assert.equal(react.data.counts['❤️'],1);
 const comment=await parsed(await request('/api/posts/'+post.id+'/comments','POST',{name:'Reader',body:'What a thoughtful tiny note.'}));assert.equal(comment.data.state,'pending');
 const publicComments=await parsed(await request('/api/posts/'+post.id+'/comments'));assert.equal(publicComments.data.length,0);
 const pending=await parsed(await request('/api/admin/comments','GET',undefined,cookie));assert.equal(pending.data.length,1);
 const approved=await parsed(await request('/api/admin/comments/'+pending.data[0].id+'/approve','POST',{},cookie));assert.equal(approved.data.state,'approved');
 const after=await parsed(await request('/api/posts/'+post.id+'/comments'));assert.equal(after.data.length,1);
 const status=await parsed(await request('/api/admin/status','PUT',{label:'Testing the corner',detail:'Everything is local and real.',isActive:true},cookie));assert.equal(status.data.label,'Testing the corner');
 const publicStatus=await parsed(await request('/api/status'));assert.equal(publicStatus.data.status.label,'Testing the corner');
 const stream=await fetch(base+'/api/realtime/stream');assert.equal(stream.headers.get('content-type'),'text/event-stream');stream.body.cancel();
 const sitemap=await(await fetch(base+'/sitemap.xml')).text();assert.ok(sitemap.includes('/post/'+post.slug));assert.ok(!sitemap.includes('/admin'));
 const signOut=await parsed(await request('/api/admin/logout','POST',{},cookie));assert.equal(signOut.data.authenticated,false);
 const afterLogout=await parsed(await request('/api/admin/posts','GET',undefined,cookie));assert.equal(afterLogout.status,401);
 console.log('HTTP integration: owner login, create, publish, search, reactions, moderation, status, SSE, sitemap and logout verified');
});
