import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { passwordHash } from '../src/auth.mjs';
import { identityInternals } from '../src/identity.mjs';

const cwd=path.dirname(fileURLToPath(new URL('../package.json',import.meta.url)));
const ownerEmail='owner-integration@corner.example';
const ownerPassword='Http-Owner-Strong-Passphrase#2026';
const memberPassword='Http-Member-Strong-Passphrase#2026';
const staffPassword='Http-Staff-Strong-Passphrase#2026';
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const mail=(file,subject)=>{
  const items=fs.readFileSync(file,'utf8').trim().split('\n').map(x=>JSON.parse(x));
  const item=items.filter(x=>x.subject.includes(subject)).at(-1);
  assert.ok(item,subject+' mail sent');
  const url=item.text.match(/https?:\/\/\S+/)?.[0];
  assert.ok(url,'has URL');
  return new URLSearchParams(new URL(url).hash.slice(1)).get('token');
};

test('real HTTP identity: staged member enrollment, MFA-gated studio, profile, account pages and cookies',async t=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'corner-identity-http-'));
  const mailbox=path.join(dir,'mail.jsonl');fs.writeFileSync(mailbox,'');
  const port=47900+Math.floor(Math.random()*950),base=`http://127.0.0.1:${port}`;
  const env={...process.env,HOST:'127.0.0.1',PORT:String(port),DB_PATH:path.join(dir,'identity.db'),DATA_DIR:dir,
    SITE_URL:base+'/corner',CORNER_BASE_PATH:'/corner',DEMO_CONTENT:'0',NODE_ENV:'test',TRUST_PROXY:'0',
    CORNER_AUTH_TEST_OUTBOX:mailbox,CORNER_AUTH_REGISTRATION_ENABLED:'1',ADMIN_EMAIL:ownerEmail,ADMIN_PASSWORD_HASH:passwordHash(ownerPassword),SESSION_SECRET:crypto.randomBytes(42).toString('hex')};
  const server=spawn(process.execPath,['--no-warnings','src/server.mjs'],{cwd,env,stdio:['ignore','pipe','pipe']});
  const logs=[];server.stderr.on('data',chunk=>logs.push(String(chunk)));
  t.after(async()=>{server.kill('SIGTERM');await wait(120);fs.rmSync(dir,{recursive:true,force:true})});
  let healthy=false;for(let i=0;i<80;i++){if(server.exitCode!==null)break;try{if((await fetch(base+'/corner/api/health')).ok){healthy=true;break}}catch{}await wait(90)}
  assert.equal(healthy,true,'test server started: '+logs.join('').slice(0,700));
  const go=async(route,{method='GET',data,cookie,origin=true}={})=>{
    const headers={accept:'application/json'};
    if(data!==undefined)headers['content-type']='application/json';
    if(cookie)headers.cookie=cookie;
    if(origin&&method!=='GET')headers.origin=base;
    return fetch(base+'/corner'+route,{method,headers,body:data===undefined?undefined:JSON.stringify(data),redirect:'manual'});
  };
  const json=async(reply)=>({status:reply.status,cookie:reply.headers.get('set-cookie'),body:await reply.json()});
  const signup=await go('/register');assert.equal(signup.status,200);
  assert.match(await signup.text(),/data-account-form="register"/);
  const roleRequest=await json(await go('/api/v1/auth/register',{method:'POST',data:{name:'API Member',email:'member-api@example.net',password:memberPassword,role:'owner'}}));
  assert.equal(roleRequest.status,202);
  const notVerified=await json(await go('/api/v1/auth/login',{method:'POST',data:{email:'member-api@example.net',password:memberPassword}}));
  assert.equal(notVerified.status,403);assert.equal(notVerified.body.error.code,'EMAIL_NOT_VERIFIED');
  const verified=await json(await go('/api/v1/auth/email/verify',{method:'POST',data:{token:mail(mailbox,'Verify')}}));
  assert.equal(verified.status,200);
  const memberLogin=await json(await go('/api/v1/auth/login',{method:'POST',data:{email:'member-api@example.net',password:memberPassword}}));
  assert.equal(memberLogin.status,200);
  assert.equal(memberLogin.body.data.user.role,'member');
  assert.match(memberLogin.cookie,/corner_member_session=/);
  assert.match(memberLogin.cookie,/SameSite=Strict/);
  assert.match(memberLogin.cookie,/Path=\/corner/);
  const memberCookie=memberLogin.cookie.split(';')[0];
  const unauthorized=await json(await go('/api/v1/admin/overview',{cookie:memberCookie}));
  assert.equal(unauthorized.status,401);
  const forgedCookie=memberCookie.replace(/^corner_member_session=/,'corner_session=');
  const forbidden=await json(await go('/api/v1/admin/overview',{cookie:forgedCookie}));
  assert.equal(forbidden.status,403,'forged admin cookie cannot elevate member role');
  const spoofedAdmin=await go('/admin',{cookie:forgedCookie});
  assert.equal(spoofedAdmin.status,200);
  assert.match(await spoofedAdmin.text(),/id="admin-login"/,'admin page does not reveal studio to forged member');
  const profile=await go('/profile',{cookie:memberCookie});
  assert.equal(profile.status,200);assert.match(profile.headers.get('cache-control'),/no-store/);
  assert.match(await profile.text(),/member-api@example.net/);
  const routeCss=await go('/account.css');assert.equal(routeCss.status,200);
  const routeJs=await go('/account.js');assert.equal(routeJs.status,200);
  const update=await json(await go('/api/v1/me',{method:'PATCH',cookie:memberCookie,data:{displayName:'Updated API Member',bio:'Hello safely',locale:'te',emailUpdates:true,role:'owner'}}));
  assert.equal(update.status,200);assert.equal(update.body.data.role,'member');
  assert.equal(update.body.data.displayName,'Updated API Member');
  const ownerLogin=await json(await go('/api/admin/login',{method:'POST',data:{email:ownerEmail,password:ownerPassword}}));
  assert.equal(ownerLogin.status,200);
  let ownerCookie=ownerLogin.cookie.split(';')[0];
  const blockedInvite=await json(await go('/api/v1/admin/invitations',{method:'POST',cookie:ownerCookie,data:{email:'staff@example.net',role:'moderator'}}));
  assert.equal(blockedInvite.status,403);assert.equal(blockedInvite.body.error.code,'MFA_REQUIRED');
  const enrollOwner=await json(await go('/api/v1/auth/mfa/setup',{method:'POST',cookie:ownerCookie,data:{}}));
  assert.equal(enrollOwner.status,200);
  const ownerCode=identityInternals.totpAt(enrollOwner.body.data.secret,Math.floor(Date.now()/30000));
  const activatedOwner=await json(await go('/api/v1/auth/mfa/activate',{method:'POST',data:{challenge:enrollOwner.body.data.challenge,code:ownerCode}}));
  assert.equal(activatedOwner.status,200);
  assert.equal((await json(await go('/api/v1/admin/overview',{cookie:ownerCookie}))).status,401,'old pre-MFA owner session revoked');
  ownerCookie=activatedOwner.cookie.split(';')[0];
  const post=await json(await go('/api/v1/admin/posts',{method:'POST',cookie:ownerCookie,data:{title:'Identity test record',body:'Private tests and security checks',type:'build'}}));
  assert.equal(post.status,201);const id=post.body.data.id;
  const published=await json(await go(`/api/v1/admin/posts/${id}/publish`,{method:'POST',cookie:ownerCookie,data:{}}));
  assert.equal(published.status,200);
  const mark=await json(await go('/api/v1/me/bookmarks',{method:'POST',cookie:memberCookie,data:{postId:id}}));
  assert.equal(mark.status,200);
  const books=await json(await go('/api/v1/me/bookmarks',{cookie:memberCookie}));
  assert.equal(books.body.data.length,1);
  const invalidOrigin=await json(await go('/api/v1/me',{method:'PATCH',origin:false,cookie:memberCookie,data:{displayName:'Hacker'}}));
  assert.equal(invalidOrigin.status,403);
  const inviteByMember=await json(await go('/api/v1/admin/invitations',{method:'POST',cookie:memberCookie,data:{email:'staff@example.net',role:'admin'}}));
  assert.equal(inviteByMember.status,401);
  const invited=await json(await go('/api/v1/admin/invitations',{method:'POST',cookie:ownerCookie,data:{email:'staff@example.net',role:'moderator'}}));
  assert.equal(invited.status,202);
  const staff=await json(await go('/api/v1/auth/admin/register',{method:'POST',data:{token:mail(mailbox,'invitation'),name:'Review Moderator',email:'staff@example.net',password:staffPassword,role:'owner'}}));
  assert.equal(staff.status,201);
  const firstStaff=await json(await go('/api/v1/auth/admin/login',{method:'POST',data:{email:'staff@example.net',password:staffPassword}}));
  assert.equal(firstStaff.status,200);assert.equal(firstStaff.body.data.mfaSetupRequired,true);
  const startMfa=await json(await go('/api/v1/auth/mfa/setup',{method:'POST',data:{challenge:firstStaff.body.data.challenge}}));
  assert.equal(startMfa.status,200);
  const otp=identityInternals.totpAt(startMfa.body.data.secret,Math.floor(Date.now()/30000));
  const finish=await json(await go('/api/v1/auth/mfa/activate',{method:'POST',data:{challenge:startMfa.body.data.challenge,code:otp}}));
  assert.equal(finish.status,200);
  assert.equal(finish.body.data.user.role,'moderator');
  const moderatorCookie=finish.cookie.split(';')[0];
  const canModerate=await json(await go('/api/v1/admin/comments',{cookie:moderatorCookie}));
  assert.equal(canModerate.status,200);
  const cannotPost=await json(await go('/api/v1/admin/posts',{cookie:moderatorCookie}));
  assert.equal(cannotPost.status,403);
  const withoutOtp=await json(await go('/api/admin/login',{method:'POST',data:{email:'staff@example.net',password:staffPassword}}));
  assert.equal(withoutOtp.status,428,'legacy admin login enforces MFA too');
  const logout=await json(await go('/api/v1/auth/logout',{method:'POST',cookie:memberCookie,data:{}}));
  assert.equal(logout.status,200);
  assert.equal((await json(await go('/api/v1/me',{cookie:memberCookie}))).status,401);
  console.log('HTTP identity accepted: role isolation, invite+MFA, legacy admin, profile, bookmarks, CSRF and private no-store pages');
});
