import test from 'node:test';
import assert from 'node:assert/strict';
import { Store } from '../src/store.mjs';
import { V3Engagement } from '../src/v3-engagement.mjs';
test('V3 follows use one-use verification and unsubscribe', async t=>{
 const store=new Store(':memory:');t.after(()=>store.close());
 const sent=[];
 const v3=new V3Engagement(store,{env:{CORNER_V3_FOLLOW_ENCRYPTION_KEY:'separate-long-random-test-key-for-v3-subscribers-2026',SESSION_SECRET:'session-secret-stays-unrelated-to-encrypted-email',SITE_URL:'https://example.test/corner',CORNER_V3_FOLLOW:'1'},sendMail:async mail=>sent.push(mail)});
 await assert.rejects(v3.follow({email:'reader@example.test'}),{code:'CONSENT_REQUIRED'});
 const pending=await v3.follow({email:'reader@example.test',consent:true,topics:['notes']});
 assert.equal(pending.accepted,true);
 assert.equal(sent.length,1);
 const verify=new URL(sent[0].text.match(/https?:\/\/[^\s]+/)[0]).hash.split('=')[1];
 assert.equal(v3.verifyFollow(verify).verified,true);
 const again=await v3.follow({email:'reader@example.test',consent:true,topics:['notes']});
 assert.deepEqual(again,pending,'public response does not reveal existing subscription');
 assert.equal(sent.length,1,'already active subscriber receives no duplicate email');
 assert.throws(()=>v3.verifyFollow(verify),{code:'TOKEN_INVALID'});
 await v3.requestUnsubscribe({email:'reader@example.test'});
 assert.equal(sent.length,2);
 const token=new URL(sent[1].text.match(/https?:\/\/[^\s]+/)[0]).hash.split('=')[1];
 assert.equal(v3.unsubscribeFollow(token).unsubscribed,true);
 assert.throws(()=>v3.unsubscribeFollow(token),{code:'TOKEN_INVALID'});
 assert.equal(store.one('SELECT state FROM v3_follows').state,'unsubscribed');
 assert.ok(!store.one('SELECT email_cipher FROM v3_follows').email_cipher.includes('reader@example.test'));
});

test('separate encryption key survives session rotation and bounces suppress sending',async t=>{
 const store=new Store(':memory:');t.after(()=>store.close());
 const sent=[];
 const originalEnv={CORNER_V3_FOLLOW:'1',CORNER_V3_FOLLOW_ENCRYPTION_KEY:'a-fixed-dedicated-secret-at-least-32-chars-2026',SESSION_SECRET:'first-session-secret-2026',SITE_URL:'https://example.test/corner'};
 assert.throws(()=>new V3Engagement(store,{env:{CORNER_V3_FOLLOW:'1',SESSION_SECRET:'first-session-secret-2026'}}),/dedicated/i);
 const v3=new V3Engagement(store,{env:originalEnv,sendMail:async item=>sent.push(item)});
 const first=await v3.follow({email:'rotated@example.test',consent:true});
 assert.equal(first.accepted,true);
 const link=new URL(sent[0].text.match(/https?:\\/\\/[^\\s]+/)[0]);
 v3.verifyFollow(link.hash.slice(7));
 const afterRotation=new V3Engagement(store,{env:{...originalEnv,SESSION_SECRET:'second-session-secret-after-rotation'},sendMail:async item=>sent.push(item)});
 const existing=await afterRotation.follow({email:'rotated@example.test',consent:true});
 assert.deepEqual(existing,first);
 assert.equal(sent.length,1,'existing email recognized with a rotated session secret');
 store.exec("UPDATE v3_follows SET state='bounced'");
 const bounce=await afterRotation.follow({email:'rotated@example.test',consent:true});
 assert.deepEqual(bounce,first);
 assert.equal(sent.length,1,'suppressed bounced address receives no email');
});
