import test from 'node:test';
import assert from 'node:assert/strict';
import {Store} from '../src/store.mjs';
import {WishesStudio} from '../src/v3-wishes.mjs';
import {wishesStudioPage} from '../src/v3-wishes-ui.mjs';
const owner={id:'owner',role:'owner'},member={id:'member',role:'member'};
test('Wishes Studio stays disabled and prevents member access',t=>{
 const s=new Store(':memory:');t.after(()=>s.close());
 const wishes=new WishesStudio(s,{env:{CORNER_V3_WISHES:'0'}});
 assert.throws(()=>wishes.create(owner,{title:'A wish',body:'A genuine moment'}),{code:'FEATURE_DISABLED'});
 wishes.env.CORNER_V3_WISHES='1';
 assert.throws(()=>wishes.list(member),{code:'OWNER_REQUIRED'});
});
test('owner wish draft, preview, optimistic locking and scheduled publication are safe',t=>{
 const s=new Store(':memory:');t.after(()=>s.close());
 const w=new WishesStudio(s,{env:{CORNER_V3_WISHES:'1'}});
 const draft=w.create(owner,{title:'A quiet celebration',body:'You deserve the lovely things ahead.',timezone:'UTC'});
 assert.equal(draft.type,'wish');assert.equal(draft.state,'draft');
 assert.equal(w.list(owner).length,1);
 const html=wishesStudioPage(w,owner);
 assert.match(html,/data-wish-studio/);assert.match(html,/PRIVATE PREVIEW/);
 assert.match(html,/v3w-form/);assert.doesNotMatch(html,/script[^>]+onerror=/);
 const before=s.all("SELECT * FROM posts WHERE state='published'");
 assert.match(w.preview(owner,{title:'Private wish',body:'Hello there'}).reminder,/nothing has been published/i);
 assert.equal(s.all("SELECT * FROM posts WHERE state='published'").length,before.length);
 assert.throws(()=>w.update(owner,draft.id,{...draft,title:'Overwritten',version:999}),{code:'VERSION_CONFLICT'});
 const updated=w.update(owner,draft.id,{title:'An edited celebration',body:'Something lovely is coming soon',timezone:'UTC',version:draft.version});
 assert.ok(updated.version>draft.version);
 const stamp='2035-05-01T10:30';
 const scheduled=w.schedule(owner,draft.id,{version:updated.version,localTime:stamp,timezone:'UTC',recurrence:'none'});
 assert.equal(scheduled.state,'scheduled');
 assert.equal(w.get(owner,draft.id).state,'scheduled');
 assert.equal(s.getFeed().items.length,0);
 s.tick('2035-05-01T10:31:00.000Z');
 assert.equal(s.getFeed().items.length,1,'One publication, never automatic email');
 assert.equal(s.tick('2035-05-01T10:31:02.000Z').length,0,'No duplicate');
 const copy=w.duplicate(owner,draft.id);
 assert.equal(copy.state,'draft');
 assert.equal(s.getFeed().items.length,1,'Duplicating is private');
 assert.equal(w.archive(owner,copy.id).state,'archived');
});
